### ISSUE TITLE
Users sometimes report that (cupid-dev) can not find (cupid-analysis)

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CUPiD#102]
At least two users have run into an issue where running

```
(cupid-dev) $ cupid-run
```

Raises the error

```
Environment cupid-analysis specified for adf_quick_run.ipynb could not be found
```

(for every notebook, not just `adf_quick_run.ipynb`). The fix seems to be to run the following

```bash
$ conda activate cupid-analysis
(cupid-analysis) $ python -m ipykernel install --user --name=cupid-analysis
```

We should add that to the documentation somewhere

**Comment by TeaganKing** [comment]
FYI Isla also just ran into this error.
