### ISSUE TITLE
Images for config file were showing up during testing but are not showing up in documentation

### ISSUE THREAD

**Issue by TeaganKing** [NCAR/CUPiD#133]
Upon merging #128 , the images of the configuration file showed up locally during testing but did not show up on our [documentation page ](https://ncar.github.io/CUPiD/config.html)when the PR was actually merged.

**Comment by mnlevy1981** [comment]
It looks like the image link in the markdown and html is

```html
<img src="[../../../images/config_1.png](view-source:https://ncar.github.io/images/config_1.png)" alt="CUPiD Config 1" width=1000 />
```

But https://ncar.github.io/CUPiD/config.html isn't three levels deep. I think what we need to do is have `conf.py` copy all the images into `docs/image` (and hope that Sphinx then copies them into `docs/_build/html/images`), and then use


```html
<img src="[images/config_1.png](view-source:https://ncar.github.io/images/config_1.png)" alt="CUPiD Config 1" width=1000 />
```

**Comment by mnlevy1981** [comment]
Actually, it looks like `_static/images` is already copied over... so have `conf.py` copy `${CUPID}/images/*` into `${CUPID}/docs/_static/images/` and then use

```html

```html
<img src="[_static/images/config_1.png](view-source:https://ncar.github.io/images/config_1.png)" alt="CUPiD Config 1" width=1000 />
```
