### ISSUE TITLE
 Examples For Adding Your Own Plots With API

### ISSUE THREAD

**Issue by TeaganKing** [NCAR/CUPiD#15]

**Comment by rmshkv** [comment]
A starting point is [here](https://nbscuid.readthedocs.io/en/latest/addingnotebookstocollection.html), though it might be a bit out of date, use with caution :)

**Comment by mnlevy1981** [comment]
Covered in the [documentation](https://ncar.github.io/CUPiD/addingnotebookstocollection.html)
