### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by TeaganKing** [NCAR/CUPiD#38]
Some documentation currently lives here: https://nbscuid.readthedocs.io/en/latest/

It'd be great to update this to reflect newer code structure.

**Comment by TeaganKing** [comment]
The documentation currently lives here: https://ncar.github.io/CUPiD/index.html

We should also figure out how to directly add the readme file to `index.rst` (rather than just include hyperlink), as @rmshkv suggested!

**Comment by anissa111** [comment]
> The documentation currently lives here: [ncar.github.io/CUPiD/index.html](https://ncar.github.io/CUPiD/index.html)
> 
> We should also figure out how to directly add the readme file to `index.rst` (rather than just include hyperlink), as @rmshkv suggested!

I can take this on!

**Comment by TeaganKing** [comment]
The documentation for setting up a new notebook that is compatible with CUPiD is now complete, and the readme is now on our documentation page, as well, as mentioned in comments above.

The next item to do would be to focus on including specific function documentation with `sphinx` and `readthedocs`.

**Comment by TeaganKing** [comment]
Additionally, we should add an 'adding scripts' page to the documentation

**Comment by mnlevy1981** [comment]
Replaced with #73 and #74
