### ISSUE TITLE
Add flags to run particular component diagnostics

### ISSUE THREAD

**Issue by TeaganKing** [NCAR/CUPiD#4]
Allow users to specify which diagnostics they want to run.

**Comment by rmshkv** [comment]
We might have accidentally duplicated this issue...covered by https://github.com/NCAR/CUPiD/issues/72 and https://github.com/NCAR/CUPiD/issues/63, which are being addressed by https://github.com/NCAR/CUPiD/pull/88

**Comment by TeaganKing** [comment]
Good catch, thanks @rmshkv !
