### ISSUE TITLE
Keep conda environment files in same directory

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CUPiD#40]
The development environment for actually running CUPiD is in `nbscuid/` (`cupid/` once #39 is accepted), while the environment used by the analysis tools is in the top level. I think we probably want to create a new `env/` or `environments/` directory and put both yaml files in that new location.

**Comment by TeaganKing** [comment]
As noted in @rmshkv 's suggestion in #39 , perhaps we should also rename the environment spec YAML file to `environment.yaml`, and then just name the actual environment that it describes as `cupid-analysis`.
