### ISSUE TITLE
for the cupid-dev environment, packages are installed by pip instead of conda

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CUPiD#43]
[`dev-environment.yml`](https://github.com/NCAR/CUPiD/blob/main/cupid/dev-environment.yml) installs `python` and `pip`, and then uses `pip` to install all the dependencies listed in [`pyproject.toml`](https://github.com/NCAR/CUPiD/blob/main/pyproject.toml). If we list those dependencies in the YAML file, then conda can install them and pip will realize they are available already.

**Comment by katiedagon** [comment]
it may also help to use mamba for creating the cupid_analysis environment, it was quite slow even using the updated conda version on my end
