### ISSUE TITLE
Jupyter Books without code.

### ISSUE THREAD

**Issue by dabail10** [NCAR/CUPiD#60]
It would be really nice to have an option to hide the code on the final Jupyter Book HTML. This is nicer for the scientists to look at.

**Comment by kafitzgerald** [comment]
This should be fairly easy to do: 
* https://jupyterbook.org/en/stable/interactive/hiding.html
* https://jupyterbook.org/en/stable/content/metadata.html#jupyter-cell-tags

I'm guessing the hidden option would be better than fulling removing the full code cells.
