### ISSUE TITLE
Add link to home page on the documentation sidebar

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CUPiD#66]
After merging #65 and #62, the sidebar looks like

![sidebar](https://github.com/NCAR/CUPiD/assets/4297161/cc9d3157-d65d-42ed-9c4c-e5ddd80bdfc5)

So if you click on the "Adding New Notebooks" link, there isn't an easy way to return to the homepage.

**Comment by rmshkv** [comment]
Clicking on the logo does take you back, but I agree that that's not clear - @anissa111 do you know the syntax to set this up?

**Comment by TeaganKing** [comment]
I think this was resolved, so I will close the issue.
