### ISSUE TITLE
Pull NCAR-specific info out of README

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CUPiD#69]
Now that `README.md` is included on the CUPiD webpage, we should separate out the `Looking at Output` section to an `NCAR_tips.md` file or something. Maybe it should only live in the documentation, and not in the main repo?

**Comment by TeaganKing** [comment]
I think this is complete (see https://github.com/NCAR/CUPiD/commit/214945977ecd648c9badf8af6230a73166f3e4b8)
