### ISSUE TITLE
cupid-clear command?

### ISSUE THREAD

**Issue by rmshkv** [NCAR/CUPiD#85]
It might be nice to have a simple command along the lines of `cupid-clear config.yml` that manually clears the computed_notebooks folder specified by a given config file. Ploomber's caching functionality is handy but doesn't seem to work the way we need for changes to executed notebooks, and I've found myself having to manually delete the output notebooks a lot to get them to rerun, so this might speed things up!

**Comment by shivaniikum** [comment]
I am interested in working on this issue.
